name: IcarusMod
version: 0.0.0
description: The custom hook in plugin for the Superior Freedom Network linking to TotalFreedomMod
depend: [TotalFreedomMod]
authors: [Wild1145, Camzie99, Hockeyfan360]
main: com.superiornetworks.icarus.IcarusMod

commands:
  icarusmod:
    description: Mostly for test usage, but will prove that the commands actually are running as expected.
    usage: /<command>
  wetoggle:
    desctiption: Toggles WE.
    usage: /<command>
  busy:
    description: Puts you in the busy status.
    usage: /<command>