name: IcarusMod
version: 0.0.0
description: The custom hook in plugin for the Superior Freedom Network linking to TotalFreedomMod
depend: [TotalFreedomMod, CoreProtect]
authors: [Wild1145, Camzie99, Hockeyfan360]
main: com.superiornetworks.icarus.IcarusMod

commands:
  icarusmod:
    description: Mostly for test usage, but will prove that the commands actually are running as expected.
    usage: /<command>
  wetoggle:
    desctiption: Toggles WE.
    usage: /<command>
  busy:
    description: Puts you in the busy status.
    usage: /<command>
  icmtoggle:
    description: Allows you to toggle certain aspects of the IcarusMod
    usage: /toggle <setting>
  doomhammer:
    description: Give yourself a DoomHammer.
    usage: /doomhammer